import { FormEvent, useMemo, useState } from "react";
import { Link } from "wouter";
import {
  ArrowLeft, Baby, CalendarCheck, Check, ChevronDown, ChevronLeft, ChevronRight,
  CircleCheck, Clock3, HeartPulse, Instagram, MapPin, Menu, MessageCircle,
  Phone, Quote, ShieldCheck, Sparkles, Stethoscope, Syringe, X, Zap,
} from "lucide-react";

const phone = "01111447874";
const whatsappNumber = "201111447874";
const whatsappMessage = encodeURIComponent("مرحبًا د. مينا عادل، أرغب في حجز موعد للكشف.");
const heroImage = "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?auto=format&fit=crop&w=1200&q=88";
const doctorImage = "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&w=900&q=88";
const clinicImage = "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1200&q=88";
const smileImage = "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?auto=format&fit=crop&w=1000&q=88";
const detailImage = "https://images.unsplash.com/photo-1588776814546-daab30f310ce?auto=format&fit=crop&w=1000&q=88";

type Service = { icon: typeof Stethoscope; number: string; title: string; description: string; items: string[]; image: string; tone: string };
const services: Service[] = [
  { icon: Stethoscope, number: "01", title: "علاج الأسنان", description: "حلول هادئة ومدروسة للحفاظ على صحة أسنانك وراحتك.", items: ["علاج العصب والجذور", "الحشو وعلاج التسوس", "علاج اللثة"], image: detailImage, tone: "blue" },
  { icon: Sparkles, number: "02", title: "تجميل الأسنان", description: "نصمم ابتسامة طبيعية تنسجم مع ملامحك وتمنحك ثقة أكبر.", items: ["ابتسامة هوليود", "الفينير واللومينير", "تبييض الأسنان"], image: smileImage, tone: "mint" },
  { icon: Syringe, number: "03", title: "زراعة الأسنان", description: "خيارات تعويضية مدروسة للأسنان المفقودة بعد التقييم المناسب.", items: ["زراعة الأسنان", "تعويض الأسنان المفقودة", "حلول الأسنان المكسورة"], image: clinicImage, tone: "navy" },
  { icon: Zap, number: "04", title: "تقويم الأسنان", description: "خطط تقويم تناسب الأطفال والكبار وتدعم ابتسامة متوازنة.", items: ["التقويم الثابت", "التقويم الشفاف", "تقويم الأطفال والكبار"], image: heroImage, tone: "sky" },
  { icon: HeartPulse, number: "05", title: "التركيبات", description: "تركيبات ثابتة ومتحركة باهتمام بالتفاصيل والوظيفة والمظهر.", items: ["التيجان والجسور", "التركيبات الثابتة والمتحركة", "المدعمة بالزرعات"], image: detailImage, tone: "blue" },
  { icon: Baby, number: "06", title: "أسنان الأطفال", description: "بداية لطيفة ومطمئنة لعادات صحية تدوم مع طفلك.", items: ["الكشف والمتابعة", "علاج تسوس الأطفال", "العناية اليومية"], image: smileImage, tone: "mint" },
];

const branches = [
  { name: "فرع الهرم", area: "الهرم – الجيزة", accent: "01" },
  { name: "فرع الشيخ زايد", area: "الشيخ زايد – الجيزة", accent: "02" },
  { name: "فرع العياط", area: "العياط – الجيزة", accent: "03" },
  { name: "فرع حلوان", area: "حلوان – القاهرة", accent: "04" },
];
const faqs = [
  { question: "كيف يمكنني حجز موعد؟", answer: "يمكنك إرسال طلب الحجز من النموذج، أو الاتصال مباشرة، أو مراسلتنا عبر WhatsApp. سيتواصل معك فريق العيادة لتأكيد التفاصيل." },
  { question: "هل يمكنني اختيار الفرع المناسب؟", answer: "نعم، يمكنك اختيار الفرع الأقرب لك من نموذج الحجز، ثم يراجع فريق العيادة توافر الموعد معك." },
  { question: "ما تخصصات طب الأسنان المتاحة؟", answer: "نقدم مجموعة متنوعة من خدمات علاج الأسنان وتجميلها، والتركيبات، والزراعة، والتقويم، وجراحة الفم، وأسنان الأطفال." },
  { question: "هل توجد خدمات تجميل الأسنان والزراعة؟", answer: "نعم، تشمل الخدمات ابتسامة هوليود والفينير والتبييض، بالإضافة إلى زراعة الأسنان بعد التقييم المناسب للحالة." },
  { question: "هل يمكنني التواصل عبر WhatsApp؟", answer: "بالتأكيد. استخدم زر WhatsApp الثابت أو زر التواصل في الموقع لإرسال رسالتك مباشرة." },
];

function SectionHeading({ eyebrow, title, description, align = "center" }: { eyebrow: string; title: string; description?: string; align?: "center" | "right" }) {
  return <div className={`section-heading ${align === "right" ? "text-right" : ""}`}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{description && <p>{description}</p>}</div>;
}
function Logo() {
  return <Link href="/" className="brand" aria-label="العودة إلى الرئيسية"><span className="brand-mark"><span>م</span></span><span className="brand-copy"><strong>د. مينا عادل</strong><small>طب وتجميل الأسنان</small></span></Link>;
}
function Header({ onBook }: { onBook: () => void }) {
  const [open, setOpen] = useState(false);
  const navItems = [["الرئيسية", "#top"], ["خدماتنا", "#services"], ["لماذا نحن", "#why-us"], ["الفروع", "#branches"], ["الأسئلة الشائعة", "#faq"]];
  const close = () => setOpen(false);
  return <header className="site-header"><div className="container header-inner"><Logo /><nav className={`desktop-nav ${open ? "open" : ""}`} aria-label="التنقل الرئيسي">{navItems.map(([label, href]) => <a href={href} key={href} onClick={close}>{label}</a>)}<button className="header-cta" onClick={() => { close(); onBook(); }}>احجز موعدك <ArrowLeft size={16} /></button></nav><button className="mobile-menu" aria-label={open ? "إغلاق القائمة" : "فتح القائمة"} onClick={() => setOpen(!open)}>{open ? <X size={23} /> : <Menu size={23} />}</button></div></header>;
}
function BookingForm() {
  const [submitted, setSubmitted] = useState(false);
  const [selectedBranch, setSelectedBranch] = useState("");
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true); };
  return <div className="booking-card"><div className="booking-card-head"><div><span className="eyebrow">خطوتك الأولى نحو ابتسامة أكثر ثقة</span><h3>احجز موعدك بسهولة</h3><p>أرسل بياناتك وسيتواصل معك فريق العيادة لتأكيد الموعد والتفاصيل.</p></div><span className="booking-seal"><CalendarCheck size={25} /></span></div>{submitted ? <div className="success-state"><span className="success-icon"><Check size={27} /></span><h4>تم استلام طلبك بنجاح</h4><p>شكرًا لتواصلك. طلب الحجز غير مؤكد تلقائيًا، وسيتواصل معك فريق العيادة لتأكيد الموعد.</p><div className="success-actions"><a className="btn btn-primary" href={`https://wa.me/${whatsappNumber}?text=${whatsappMessage}`} target="_blank" rel="noreferrer">أكّد عبر WhatsApp <MessageCircle size={17} /></a><button className="text-button" onClick={() => setSubmitted(false)}>إرسال طلب آخر</button></div></div> : <form onSubmit={handleSubmit} className="booking-form"><label>الاسم الكامل<input required name="name" placeholder="اكتب اسمك هنا" /></label><label>رقم الهاتف<input required name="phone" type="tel" inputMode="tel" placeholder="01xxxxxxxxx" /></label><label>الفرع<select required name="branch" value={selectedBranch} onChange={(e) => setSelectedBranch(e.target.value)}><option value="" disabled>اختر الفرع المناسب</option>{branches.map((branch) => <option key={branch.name} value={branch.name}>{branch.name}</option>)}</select></label><label>الخدمة المطلوبة<select required name="service" defaultValue=""><option value="" disabled>اختر الخدمة</option>{services.map((service) => <option key={service.title} value={service.title}>{service.title}</option>)}</select></label><label>التاريخ<input required name="date" type="date" /></label><label>الوقت المفضل<input required name="time" type="time" /></label><label className="full-field">ملاحظات إضافية <span className="optional">اختياري</span><textarea name="notes" rows={3} placeholder="شاركنا أي تفاصيل تساعدنا على خدمتك بشكل أفضل" /></label><button type="submit" className="btn btn-primary form-submit">إرسال طلب الحجز <ArrowLeft size={17} /></button><p className="form-note"><ShieldCheck size={14} /> نستخدم بياناتك للتواصل بخصوص طلب الحجز فقط.</p></form>}</div>;
}
function BeforeAfter() {
  const [position, setPosition] = useState(52);
  return <div className="comparison-card"><div className="comparison-visual"><img src={smileImage} alt="ابتسامة تجريبية بعد العلاج" /><div className="comparison-before" style={{ width: `${position}%` }}><img src={detailImage} alt="صورة تجريبية قبل العلاج" /></div><div className="comparison-divider" style={{ left: `${position}%` }}><span>↔</span></div><span className="compare-label before-label">قبل <small>صورة تجريبية</small></span><span className="compare-label after-label">بعد <small>صورة تجريبية</small></span></div><input className="compare-range" type="range" min="8" max="92" value={position} onChange={(e) => setPosition(Number(e.target.value))} aria-label="مقارنة قبل وبعد" /><div className="comparison-caption"><strong>مقارنة توضيحية</strong><span>اسحب المؤشر للمقارنة — الصور المعروضة تجريبية وليست لحالات مرضى حقيقية.</span></div></div>;
}
function FaqList() {
  const [active, setActive] = useState(0);
  return <div className="faq-list">{faqs.map((faq, index) => <div className={`faq-item ${active === index ? "active" : ""}`} key={faq.question}><button onClick={() => setActive(active === index ? -1 : index)} aria-expanded={active === index}><span>{faq.question}</span><ChevronDown size={19} /></button>{active === index && <p>{faq.answer}</p>}</div>)}</div>;
}

export default function Home() {
  const [activeService, setActiveService] = useState(0);
  const [mobileBranchIndex, setMobileBranchIndex] = useState(0);
  const activeBranch = branches[mobileBranchIndex];
  const service = useMemo(() => services[activeService], [activeService]);
  const goBooking = () => document.getElementById("booking")?.scrollIntoView({ behavior: "smooth" });
  return <div id="top" className="site-shell"><Header onBook={goBooking} /><main>
    <section className="hero-section"><div className="hero-glow glow-one" /><div className="hero-glow glow-two" /><div className="container hero-grid"><div className="hero-copy"><div className="hero-kicker"><span className="pulse-dot" /> رعاية تليق بابتسامتك</div><h1>ابتسامتك تبدأ<br /><em>من هنا.</em></h1><p className="hero-lead">رعاية متكاملة لأسنانك مع د. مينا عادل، بخبرة واهتمام لتقديم حلول طب وتجميل الأسنان في بيئة مريحة وآمنة.</p><div className="hero-actions"><button className="btn btn-primary" onClick={goBooking}>احجز موعدك الآن <ArrowLeft size={18} /></button><a className="btn btn-ghost" href={`tel:${phone}`}><Phone size={17} /> اتصل بنا</a></div><div className="hero-trust"><div className="avatar-stack"><span>م</span><span>ع</span><span>+</span></div><div><strong>رعاية تبدأ بالاستماع</strong><small>خطوتك الأولى نحو ابتسامة مطمئنة</small></div></div></div><div className="hero-visual"><div className="hero-image-frame"><img src={heroImage} alt="طبيب أسنان يعمل داخل عيادة حديثة" /><div className="image-overlay" /></div><div className="hero-floating-card card-rating"><span className="rating-icon">✦</span><div><strong>رعاية متكاملة</strong><small>من الكشف إلى خطة العلاج</small></div></div><div className="hero-floating-card card-availability"><span className="available-dot" /><div><strong>نستقبلك في 4 فروع</strong><small>اختر الأقرب إليك</small></div></div><div className="hero-number"><span>01</span><small>ابتسامة<br />بثقة</small></div></div></div><div className="hero-bottom-note container"><span>مرحبًا بك في عيادة د. مينا عادل</span><span className="scroll-indicator"><i /> اسحب للاستكشاف</span></div></section>
    <section className="quick-benefits"><div className="container benefit-grid">{[[ShieldCheck, "رعاية موثوقة", "اهتمام حقيقي بكل تفاصيل زيارتك"], [Sparkles, "حلول متكاملة", "خدمات متعددة في مكان واحد"], [Clock3, "مواعيد مرنة", "نرتب وقتك بما يناسب يومك"], [MapPin, "4 فروع قريبة", "الهرم، زايد، العياط، حلوان"]].map(([Icon, title, text]) => { const IconComponent = Icon as typeof ShieldCheck; return <div className="benefit-item" key={title as string}><span className="benefit-icon"><IconComponent size={21} /></span><div><strong>{title as string}</strong><small>{text as string}</small></div></div>; })}</div></section>
    <section id="services" className="section services-section"><div className="container"><SectionHeading eyebrow="خدماتنا" title="كل ما تحتاجه ابتسامتك، بعناية واحدة" description="من العناية الأساسية إلى التفاصيل التجميلية، نساعدك على فهم الخيارات المناسبة لك بهدوء ووضوح." /><div className="services-layout"><div className="service-tabs">{services.map((item, index) => { const Icon = item.icon; return <button className={`service-tab ${activeService === index ? "active" : ""}`} key={item.title} onClick={() => setActiveService(index)}><span className="service-tab-number">{item.number}</span><span className="service-tab-icon"><Icon size={20} /></span><span>{item.title}</span><ChevronLeft className="service-tab-arrow" size={17} /></button>; })}</div><div className={`featured-service ${service.tone}`}><div className="featured-service-image"><img src={service.image} alt={service.title} /><span className="feature-tag">خدمة متخصصة</span></div><div className="featured-service-copy"><span className="eyebrow">{service.number} / {String(services.length).padStart(2, "0")}</span><h3>{service.title}</h3><p>{service.description}</p><ul>{service.items.map((item) => <li key={item}><CircleCheck size={17} /> {item}</li>)}</ul><button className="inline-link" onClick={goBooking}>اكتشف الخدمة واحجز <ArrowLeft size={16} /></button></div></div></div><div className="service-all-link"><Link href="/services">استكشف جميع الخدمات بالتفصيل <ArrowLeft size={16} /></Link></div></div></section>
    <section id="why-us" className="section why-section"><div className="container why-grid"><div className="why-visual"><div className="why-image-main"><img src={doctorImage} alt="د. مينا عادل داخل العيادة" /></div><div className="why-image-small"><img src={clinicImage} alt="تفاصيل من عيادة أسنان حديثة" /></div><div className="why-stamp"><span>م</span><small>عناية<br />تُشبهك</small></div></div><div className="why-copy"><SectionHeading align="right" eyebrow="لماذا د. مينا عادل؟" title="لأن راحتك جزء من العلاج" description="نؤمن أن تجربة المريض لا تبدأ من كرسي العلاج فقط، بل من أول سؤال واستماع حقيقي لاحتياجك." /><div className="why-points"><div><span><HeartPulse size={19} /></span><p><strong>اهتمام براحة المريض</strong><small>تجربة هادئة وشرح واضح قبل كل خطوة.</small></p></div><div><span><Sparkles size={19} /></span><p><strong>خدمات متنوعة في مكان واحد</strong><small>رعاية متكاملة تساعدك على متابعة احتياجك بسهولة.</small></p></div><div><span><Zap size={19} /></span><p><strong>تقنيات حديثة عند توفرها</strong><small>نختار ما يناسب حالتك بعد التقييم والتشخيص.</small></p></div></div><button className="btn btn-dark" onClick={goBooking}>ابدأ رحلتك معنا <ArrowLeft size={17} /></button></div></div></section>
    <section className="section journey-section"><div className="container"><SectionHeading eyebrow="رحلة المريض" title="خطوات بسيطة. اهتمام مستمر." description="نرافقك من أول مكالمة حتى تتضح أمامك الخطوة التالية." /><div className="journey-grid">{[["01", "احجز موعدك", "تواصل معنا واختر الفرع المناسب لك."], ["02", "الكشف والتقييم", "نفهم احتياجك ونقيّم حالتك بعناية."], ["03", "خطة العلاج", "نشرح الخيارات المناسبة لك بوضوح."], ["04", "ابدأ العلاج", "ننفّذ الخطة المناسبة لحالتك ووقتك."]].map(([num, title, text], index) => <div className="journey-step" key={num}><span className="journey-number">{num}</span><div className="journey-line" />{index < 3 && <span className="journey-arrow"><ArrowLeft size={16} /></span>}<h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
    <section className="section gallery-section"><div className="container gallery-grid"><div className="gallery-copy"><SectionHeading align="right" eyebrow="مقارنة توضيحية" title="التغيير يبدأ من التفاصيل" description="استخدم المؤشر لرؤية مقارنة تجريبية. الصور المعروضة للتوضيح فقط وليست حالات مرضى حقيقية." /><div className="gallery-note"><span><ShieldCheck size={18} /></span><p><strong>خصوصيتك أولًا</strong><small>لا نستخدم صور مرضى حقيقيين دون مصدر أو إذن.</small></p></div></div><BeforeAfter /></div></section>
    <section className="section testimonial-section"><div className="container testimonial-inner"><div className="quote-mark"><Quote size={35} /></div><span className="eyebrow">كلمة نحب أن تسمعها</span><h2>ابتسامتك مهمة،<br /><em>ونحن هنا لنعتني بها.</em></h2><p>هذا القسم مخصص لإضافة تقييمات المرضى الحقيقية بعد الحصول على موافقتهم.</p><div className="demo-badge">قسم التقييمات — جاهز للإضافة</div></div></section>
    <section id="branches" className="section branches-section"><div className="container"><SectionHeading eyebrow="فروعنا" title="أقرب إليك، أينما كنت" description="اختر الفرع الأنسب لك، وسيتواصل معك فريقنا لتنسيق التفاصيل." /><div className="branches-grid">{branches.map((branch) => <div className="branch-card" key={branch.name}><span className="branch-index">{branch.accent}</span><span className="branch-icon"><MapPin size={20} /></span><h3>{branch.name}</h3><p>{branch.area}</p><button onClick={goBooking}>احجز في هذا الفرع <ArrowLeft size={15} /></button><span className="branch-deco" /></div>)}</div><div className="branch-mobile-nav"><button onClick={() => setMobileBranchIndex((mobileBranchIndex - 1 + branches.length) % branches.length)} aria-label="الفرع السابق"><ChevronRight size={18} /></button><strong>{activeBranch.name}</strong><button onClick={() => setMobileBranchIndex((mobileBranchIndex + 1) % branches.length)} aria-label="الفرع التالي"><ChevronLeft size={18} /></button></div></div></section>
    <section id="booking" className="section booking-section"><div className="container booking-grid"><div className="booking-aside"><span className="eyebrow">نحن ننتظر تواصلك</span><h2>لنبدأ من<br /><em>ابتسامتك.</em></h2><p>أخبرنا بما تحتاجه، واترك لنا مهمة ترتيب الخطوة التالية معك.</p><div className="contact-mini"><a href={`tel:${phone}`}><span><Phone size={17} /></span><div><small>اتصل الآن</small><strong dir="ltr">{phone}</strong></div><ArrowLeft size={17} /></a><a href={`https://wa.me/${whatsappNumber}?text=${whatsappMessage}`} target="_blank" rel="noreferrer"><span className="whatsapp-icon"><MessageCircle size={17} /></span><div><small>راسلنا على WhatsApp</small><strong>نحن هنا لمساعدتك</strong></div><ArrowLeft size={17} /></a></div><div className="booking-aside-note"><CalendarCheck size={18} /><span>طلبك ليس موعدًا مؤكدًا حتى يتواصل معك فريق العيادة.</span></div></div><BookingForm /></div></section>
    <section id="faq" className="section faq-section"><div className="container faq-grid"><div><SectionHeading align="right" eyebrow="الأسئلة الشائعة" title="لديك سؤال؟ ابدأ من هنا" description="إجابات مختصرة تساعدك على معرفة الخطوة المناسبة قبل الزيارة." /><a className="faq-contact" href={`https://wa.me/${whatsappNumber}?text=${whatsappMessage}`} target="_blank" rel="noreferrer">لم تجد إجابتك؟ تواصل معنا <ArrowLeft size={16} /></a></div><FaqList /></div></section>
  </main><footer className="site-footer"><div className="container footer-main"><div className="footer-brand"><Logo /><p>رعاية متكاملة لأسنانك،<br />بهدوء واهتمام.</p></div><div><h4>استكشف</h4><a href="#services">خدماتنا</a><a href="#why-us">لماذا نحن</a><a href="#branches">الفروع</a></div><div><h4>تواصل معنا</h4><a href={`tel:${phone}`} dir="ltr">{phone}</a><a href={`https://wa.me/${whatsappNumber}?text=${whatsappMessage}`} target="_blank" rel="noreferrer">WhatsApp</a><a href="#booking">احجز موعدًا</a></div><div className="footer-social"><h4>كن على تواصل</h4><p>تابع أخبار العيادة وتحديثاتها.</p><div><a href="#top" aria-label="Instagram"><Instagram size={18} /></a><a href={`https://wa.me/${whatsappNumber}?text=${whatsappMessage}`} target="_blank" rel="noreferrer" aria-label="WhatsApp"><MessageCircle size={18} /></a></div></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} د. مينا عادل لطب وتجميل الأسنان</span><span>موقع طبي تعريفي — المعلومات لا تغني عن الكشف الطبي.</span></div></footer><a className="floating-whatsapp" href={`https://wa.me/${whatsappNumber}?text=${whatsappMessage}`} target="_blank" rel="noreferrer" aria-label="تواصل معنا عبر WhatsApp"><MessageCircle size={24} /><span>WhatsApp</span></a><div className="mobile-bottom-bar"><a href={`tel:${phone}`}><Phone size={18} /><span>اتصال</span></a><a href={`https://wa.me/${whatsappNumber}?text=${whatsappMessage}`} target="_blank" rel="noreferrer"><MessageCircle size={18} /><span>WhatsApp</span></a><button onClick={goBooking}><CalendarCheck size={18} /><span>احجز الآن</span></button></div></div>;
}
